# Non-secret values CI passes to the targeted deploy apply.
# Committed on purpose (no secrets here). Change project_name per project.
# The DB password is generated by Terraform and lives in state, not here.

project_name   = "nextjs-test"
aws_region     = "us-east-1"
deploy_service = true
